project:
  type: default
  render:
    - "!about.qmd"
    - "!disclaimer.qmd"
    - "!index.qmd"
    - "!llms.qmd"
    - "!publishing-guidelines.qmd"
    - "!team.qmd"
    - "!dashboards/**"
    - "!events/**"
    - "!mentions/**"
    - "!posts/**"
    - "!posters/index.qmd"
  post-render:
    - _extensions/bbucior/docposter/R/chrome_pdf.R

format:
  docposter-html:
    fill-page: true
    embed-resources: true
