project:
  type: website

website:
  title: "NAIF"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - news.qmd
      - about.qmd
      - team.qmd
      - resources.qmd
      - join.qmd
      - contact.qmd
    pinned: true
  page-footer:
    center:
      - text: "&copy; ETH Library &#x00B7; Powered by Quarto"
    right:
      - text: "Disclaimer"
        href: disclaimer.qmd


format:
  html:
    theme:
      light: [cosmo, base_colors.scss, custom.scss]
    css: styles.css
    toc: true
    toc-expand: true
    toc-title: " "
    mainfont: Barlow
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    footnotes-hover: true
    anchor-sections: false
    include-after-body: traffic.html
    email-obfuscation: references



