project:
  type: default
  render:
    - "posters/**/poster.qmd"
    - "!posters/index.qmd"
  post-render:
    - _extensions/bbucior/docposter/R/chrome_pdf.R

format:
  docposter-html:
    fill-page: true
    embed-resources: true
