---
title: "News"
---

## Upcoming event and ongoing survey


* Workshop: Improving academic metadata for Swiss repositories and institutions (NAIF Track 4)
  + Date: Monday, 8 December 2025, 10:00-11:30
  + Location: Online
  + Zoom link: https://ethz.zoom.us/j/62921397842
* Survey on Swiss institutional repositories (Track 3)
  + Link to the survey: https://www.surveyhero.com/c/naif-repositories-2025
  + Deadline to complete the survey: 15 December 2025
  + Contact: [naif-survey@library.ethz.ch](mailto:naif-survey@library.ethz.ch)
  


## News

#### NAIF launches a national survey on Swiss institutional repositories
*05.11.2025*

We are launching a **national survey** to map and better understand the landscape of institutional repositories in Switzerland. 
The initiative aims to strengthen **interoperability, standardisation, and coordination** across the country’s research information ecosystem.   

The survey explores how repositories are **managed, described, and sustained,** focusing on infrastructure, metadata practices, governance, and long-term strategies.
It seeks to identify **common strengths, gaps, and challenges,** laying the groundwork for **a national roadmap** aligned with international standards and open science principles.  
 
The questionnaire is addressed to **repository managers and service leads** from Swiss higher education institutions operating repositories or CRIS systems. Each manager will be contacted directly to participate.  

To support respondents, **two Q&A sessions** will be organised: 

* 🇫🇷 Thursday, 20 November 2025, 11:00–12:00 (in French)  
* 🇩🇪 Wednesday, 26 November 2025, 15:00–16:00 (in German)  

The survey draws inspiration from major international efforts, including the [NORF Survey of Open Repositories in Ireland](https://zenodo.org/records/10390626), the [OpenAIRE / LIBER / SPARC Europe / COAR Joint Survey of Open Repositories in Europe](https://zenodo.org/records/10255559), the [COAR consultation “Crafting a Vision for European Repositories”](https://coar-repositories.org/news-updates/open-consultation-crafting-a-vision-for-european-repositories/), and the institutional repository workflow survey carried out within the Working Group 2 ([Taskforce 1: Metadata in Institutional Repositories](https://zenodo.org/records/15730917)) of the [Barcelona Declaration on Open Research Information](https://barcelona-declaration.org/).  

This will be the **first national overview** of repository maturity and practices in Switzerland. Findings will inform coordinated actions and shared services, and aggregated results will be published openly on [Zenodo within the NAIF community](https://zenodo.org/communities/naif/members) — contributing to a **stronger and more connected Swiss open science ecosystem**.  

Deadline: 15 December 2025  
Contact: [naif-survey@library.ethz.ch](mailto:naif-survey@library.ethz.ch)  
Take the survey: https://www.surveyhero.com/c/naif-repositories-2025  


#### NAIF Workshop on the responsible use of Quantitative Scientometric Indicators
*31.10.2025*

On 11^th^ of September 2025, a NAIF Workshop on the responsible use of Quantitative Scientometric Indicators (QSI) was held at ETH Zurich in the context of the 6^th^ SYoS (Swiss Year of Scientometrics) Workshop.  
The slides of a lightning talk by Ginny Barbour, Co-Chair of the Declaration on Research Assessment (DORA), on [Using Quantitative Indicators Responsibly in Research Assessment](https://doi.org/10.5281/zenodo.17481395) are now available on Zenodo.  
A [summary of the workshop and its insights](https://yearofscientometrics.ethz.ch/responsible-use-of-quantitative-scientometric-indicators-insights-from-the-6th-syos-workshop) by Martin Jaekel is available on the SYoS Blog.


#### NAIF at the SOAD Day and at the ICSTI 2025 Annual conference
*26.09.2025*

The month of September is marked by a series of events dedicated to Open Science, and we are proud to have contributed to the momentum.
We had the pleasure of presenting Track 4 of the NAIF project at the first [SOAD Day](https://soad.ch) (Swiss Open Academic Data Day) on 10 September and showcasing the technical aspects of the project at the [ICSTI](https://www.icsti.org) 2025 Annual conference (International Council for Scientific and Technical Information) on 19 September.  
We are thankful to the organizers and participants of both events for the opportunity to present the project and engage in insightful discussions.  
The [slides](https://doi.org/10.5281/zenodo.17142628) of the SOAD Day presentation are available on the [Zenodo community](https://zenodo.org/communities/soad) of the event.


#### Upcoming: NAIF workshops and panel discussion
*03.09.2025*

We are pleased to invite you to the following NAIF events:

* Workshop: Responsible use of quantitative indicators (NAIF Track 1)
  + Date: Thursday, 11 September 2025
  + Location: ETH Zurich
  + Registration [link](https://yearofscientometrics.ethz.ch/mc-events/syos-workshop-no-6)
* Workshop: Improving academic metadata for Swiss repositories and institutions (NAIF Track 4)
  + Date: Wednesday, 15 October 2025
  + Location: University of Neuchâtel
  + Registration [link](https://forms.gle/23kzvv1kubBDXpHp6)
* From Policy to Practice: Building a National Open Research Information Framework in Switzerland (NAIF Track 2)
  + Date: Wednesday, 5 November 2025
  + Location: University of Zurich
  + Program: [Flyer](https://www.ub.uzh.ch/dam/jcr:5ee157b5-eba2-4b11-b1c9-d5bb7351d84c/Flyer_Panel-discussion_From-policy-to-practice.pdf)
  + Registration [link](https://ema.uzh.ch/RLX4H)


#### NAIF Information Event
*03.09.2025*

We would like to thank the more than fifty participants at the **NAIF information event** for their interest.  
The slides of the presentation are now [available](https://github.com/eth-library/naif/raw/main/documents/2025-08-28_NAIF_information_event.pdf). 


#### Upcoming: NAIF information event
*04.08.2025*

We are pleased to invite you to the **NAIF information event** taking place on Thursday, 28 August 2025 at 4pm, where we will present the project and its goals.  
Registration is no longer available.
  
The information event is open to anyone who is interested.


#### Project start
*07.2025*

We are pleased to announce the launch of the NAIF project.
